### ISSUE TITLE
Pass monitor id as argument to script file

### ISSUE THREAD

**Issue by patrikha** [coffebar/hyprland-monitor-attached#1]
Would be good if the attached monitor name (e.g. HDMI-A-1 or similar) would be passed to the script...

**Comment by coffebar** [comment]
Ok, I will do it soon.
Meantime, you can grep monitors from  hyprctl in your script:

```bash
# stop if attached monitor is not HDMI-A-1
hyprctl monitors | grep HDMI-A-1 || exit
```
