### ISSUE TITLE
Log activities / errors

### ISSUE THREAD

**Issue by gvolpe** [coffebar/hyprland-monitor-attached#6]
**Is your feature request related to a problem? Please describe.**
I've had this working fine for a while, but then it stopped working altogether (perhaps on a Hyprland upgrade) and there's no way of knowing what's going on as far as I know.

**Describe the solution you'd like**
Are there any logs relevant to `hyprland-monitor-attached`? If not, is it possible to add this as a feature? It would be good to troubleshoot this kind of issues.

**Describe alternatives you've considered**
N/A

**Additional context**
Running the latest release `v0.16`.

**Comment by coffebar** [comment]
kill it and run in console to see stderr and stdout, or redirect it to file.

```
killall hyprland-monitor-attached
hyprland-monitor-attached PATH_TO_SCRIPT
```
You should see errors if there is something wrong. Also, you can see output from your script. 
For example, if I add ```echo "-> $1"``` to my script, then attach monitor, I can see this output in console where **hyprland-monitor-attached** is started:

> -> HDMI-A-1

**Comment by gvolpe** [comment]
Thanks for the quick response! Redirecting the output to a file works 👍🏽 

The script is working fine, I just realized that when I unplug my HDMI cable, the reported monitor is `FALLBACK` instead of `eDP-1`, so my entire logic was falling apart. 

---

For completeness, here's how I'm running it:

```ini
exec-once=/nix/store/qp7jnnppbmc8n36s4wchxmggnj38fmhv-hyprland-monitor-attached-0.1.6/bin/hyprland-monitor-attached /nix/store/05mg81kfq7dbax93shiwnbbrx0kijwi3-monitor-added/bin/monitor-added /nix/store/rjb3nnakhsjgz3knzpis5qpyly6qzywn-monitor-removed/bin/monitor-removed > ~/.config/hypr/monitor-attached.log 2>&1
```

Monitor added script:

```bash
#!/nix/store/vpvy79k1qq02p1vyqjk6nb89gwhxqvyb-bash-5.2p32/bin/bash
echo "Monitor added: $1"
hyprctl --batch "\
  dispatch moveworkspacetomonitor 1 DP-3;\
  dispatch moveworkspacetomonitor 2 DP-3;\
  dispatch moveworkspacetomonitor 3 DP-3;\
  dispatch moveworkspacetomonitor 4 DP-3;\
  dispatch moveworkspacetomonitor 5 DP-3;\
  dispatch moveworkspacetomonitor 6 DP-3"

hyprctl dispatch dpms off eDP-1
echo "monitor=DP-3,2560x1440@59.95,0x0,1" > $XDG_CONFIG_HOME/hypr/monitors.conf
echo "monitor=eDP-1,disable" >> $XDG_CONFIG_HOME/hypr/monitors.conf
```

Monitor removed script:

```bash
#!/nix/store/vpvy79k1qq02p1vyqjk6nb89gwhxqvyb-bash-5.2p32/bin/bash
echo "Monitor removed: $1"
echo "monitor=eDP-1,2880x1800@90,0x0,2" > $XDG_CONFIG_HOME/hypr/monitors.conf
hyprctl dispatch dpms on eDP-1
```

Replacing `eDP-1` with `FALLBACK` fixed the issue for me, appreciate your input! 🙏🏽
